services:
  darktide-mission-board:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "darktide-mission-board"
    ports:
      - ":80"
    restart: always

networks:
  default:
    external: true
    name: nginx-network